# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['desktop_agent/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'desktop_agent',
        'desktop_agent.main',
        'desktop_agent.registry',
        'desktop_agent.tools_applications',
        'desktop_agent.tools_websites',
        'desktop_agent.tools_search',
        'desktop_agent.tools_files',
        'desktop_agent.tools_pc',
        'desktop_agent.tools_windows',
        'desktop_agent.tools_clipboard',
        'desktop_agent.tools_screenshot',
        'desktop_agent.tools_camera',
        'desktop_agent.tools_browser',
        'desktop_agent.tools_coding',
        'desktop_agent.tools_system',
        'desktop_agent.tools_confirmation',
        'desktop_agent.tools_startup',
        'desktop_agent.tools_mouse',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['torch', 'torchvision', 'scipy', 'pandas', 'matplotlib', 'sklearn', 'IPython', 'jupyter', 'notebook', 'tensorboard'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='nuvi-agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
